export type EventTypes = {
  id: number,
  title: string,
  altImage: string,
  content: string,
  createdAt: string,
  finishDate: string,
  startDate: string,
  hashtag: string,
  isActive: boolean,
  modifiedAt: string,
  thumbnail: string,
  location: string,
  isHotEvent: boolean,
}
